from .encoder_dual import EncoderDualModel
from .encoder_gnn import EncoderGNNModel
from .encoder_triplet import EncoderTripletModel
from .encoder_mtb import EncoderMTBModel
from .encoder_pmtb import EncoderPMTBModel
from .encoder_fewrel import EncoderFewRelModel
from .encoder_kbp37 import EncoderKBP37Model
from .encoder_semeval2010task8 import EncoderSemEval2010Task8Model
from .encoder_tacred import EncoderTACREDModel
from .encoder_eval import EncoderGNNEval
from .multi_model import MultiModel
